name: ulusoyapps_flutter_analysis
description: Lint rules for Dart and Flutter used in Ulus Oy Apps.
version: 1.0.0
repository: https://github.com/ulusoyapps/ulusoyapps_flutter_analysis

environment:
  sdk: '>=2.17.1 <4.0.0'

dependencies:
  very_good_analysis: 4.0.0+1